// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package stocks_repository

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg *CreateOrderParams) (int64, error)
	GetOrderInfo(ctx context.Context, id int64) (*Order, error)
	GetOrderItems(ctx context.Context, orderID int64) ([]*GetOrderItemsRow, error)
	InsertOrderItem(ctx context.Context, arg *InsertOrderItemParams) error
	UpdateOrderStatus(ctx context.Context, arg *UpdateOrderStatusParams) error
}

var _ Querier = (*Queries)(nil)
